### ISSUE TITLE
Review schedplugin messages

### ISSUE THREAD

**Issue by ptrlv** [PanDAWMS/autopyfactory#6]
APF-2.4 message example:

```
Ready:in=0;activated=18,offset=0,pending=16;ret=2;Scale:in=2;factor=0.5;ret=1;MaxPerCycle:in=1;maxpercycle=50;ret=1;MinPerCycle:in=1;minpercycle=0;ret=1;StatusTest:(not test);input=1; Return=1;StatusOffline:(not offline);in=1;ret=0;MaxPending:in=1;pending=16,maxpending=100;ret=1
```

What structure do these have? The monitor needs to tokenize this so I suggest these changes:
1. semi-colon to separate scheds
2. change ; to , within a single sched
3. StatusTest Return change to ret  (to be consistent)
4. make consistent the comment part eg. (not offline)

Or can this be improved further?

**Comment by jose-caballero** [comment]
I have started working on this. I committed the changes. 
1. I have replaced ; by , inside each sched message. Therefore ; is only used to split messages from different scheds.
2. Changed Return by ret in StatusTest plugin

Any suggestion for #4?

**Comment by ptrlv** [comment]
Thanks Jose. I say go ahead and close this or any ticket once the code commit is done.

**Comment by jose-caballero** [comment]
BTW, just to avoid misunderstanding, by #4 I meant the comment "make consistent the comment part". 
Apparently github created a link to issue 4. I didn't mean to mix issues.

**Comment by ptrlv** [comment]
Github trying to be clever.

For the comment how about adding a key 'comment' which can be there or not.
SchedNameA:comment=foobar,in=1,foo=2,bar=3,ret=0;SchedNameB:in=1,foo=2,bar=3,ret=0;

**Comment by jose-caballero** [comment]
comment field implemented. 
I think that covers all requests. 
NOTE: the value for key "comment" sometimes includes whitespaces. 

Closing the issue.
